---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-quarkus-app-8-dev
  namespace: assemble-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/assemble-platforms-test-2/my-quarkus-app-8-gitops
    targetRevision: HEAD
    path: ./helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: my-quarkus-app-8-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
